### ISSUE TITLE
Grid

### ISSUE THREAD

**Issue by sullyf50** [atatanasov/gijgo-asp-net-examples#1]
Issues with post method 
Cannot get what error it says

**Comment by atatanasov** [comment]
Could tell me the name of the example that cause this issue? Did you check if the database is installed correctly on your machine?

**Comment by sullyf50** [comment]
Hi

I email u the details later on today



Sent from my iPhone

On 30 Jul 2018, at 08:21, Atanas Atanasov <notifications@github.com<mailto:notifications@github.com>> wrote:


Could tell me the name of the example that cause this issue? Did you check if the database is installed correctly on your machine?

**Comment by sullyf50** [comment]
$.ajax({
          url: '/WebSuppiler.asmx/SaveNewSuppiler', data: { record: record }, method: 'POST', dataType: "json",
        
        })
                .done(function () {
                  dialog.close();
                  grid.reload();
                })

          .fail(function (data) {
            alert('Failed to save.');
            dialog.close();

          });
      });

      $('#btnCancelSuppiler').on('click', function () {
        DialogSuppilertopen.close();
      });

This does not tell me why it’s wrong and i could not find any example which would tell me a bit more .

Thanks

it looks like it dose not even get to the SaveNewSuppiler function
